Add Swift Package Manager Support
mention-me/ios-sdk pull request #3
Opened 2020-07-20 17:50 UTC by JonathanDowning

This PR adds support for Swift Package Manager.

I kept the import name the same as for cocoa pods so usage should be identical!

2021-04-15 17:01 UTC, sjparkinson requested changes
Thanks for this suggestion @JonathanDowning, and sorry it's taken so long to review!

We'll look to merge this soon and will pick up the suggested changes if we don't hear from you.

2021-04-15 17:01 UTC, sjparkinson commented on README.md
> +To remove the dependency, select the project and open Swift Packages (which is next to Build Settings). You can add and remove packages from this tab.
Thanks for this, rather than guide the user through the menus I'd rather provide what needs to be added to `Package.swift`, as we can provide both the URL and the branch/version in one go.

We currently don't have semver compliant tag, so nudging to use the master branch until then I think makes the most sense too.

```suggestion
To install **MentionmeSwift**, just add the package as a dependency in your `Package.swift` file.

```swift
dependencies: [
    .package(url: "https://github.com/mention-me/ios-sdk.git", .branch("master"))
]
```
```

2021-04-15 17:03 UTC, sjparkinson commented on README.md
> +To remove the dependency, select the project and open Swift Packages (which is next to Build Settings). You can add and remove packages from this tab.
I don't thing GitHub's suggested change feature likes suggestions ending with <code>```</code>!

2021-04-15 20:13 UTC, JonathanDowning commented on README.md
> +To remove the dependency, select the project and open Swift Packages (which is next to Build Settings). You can add and remove packages from this tab.
All done!

2021-04-19 08:55 UTC, sjparkinson approved these changes

2021-04-19 08:55 UTC, merged